services:

  web:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SITE_URL: ${SITE_URL}
      TIME_ZONE: ${TIME_ZONE}
      TZ: ${TZ}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      X_FORWARDED_PROTO_HEADER_SET: ${X_FORWARDED_PROTO_HEADER_SET}
      USE_X_FORWARDED_HOST: ${USE_X_FORWARDED_HOST}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PS_DATABASE_URI: ${PS_DATABASE_URI}
      PS_STORAGE_PG_URI: ${PS_STORAGE_PG_URI}

  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}

  nginx:
    ports: !override
      - "8087:80"
    networks:
      - default

  powersync:
    environment:
      PS_STORAGE_PG_URI: ${PS_STORAGE_PG_URI}
      PS_JWKS_URL: http://web:8000/api/v2/powersync-keys

  celery_worker:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SITE_URL: ${SITE_URL}
      TIME_ZONE: ${TIME_ZONE}
      TZ: ${TZ}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PS_DATABASE_URI: ${PS_DATABASE_URI}
      PS_STORAGE_PG_URI: ${PS_STORAGE_PG_URI}

  celery_beat:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SITE_URL: ${SITE_URL}
      TIME_ZONE: ${TIME_ZONE}
      TZ: ${TZ}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PS_DATABASE_URI: ${PS_DATABASE_URI}
      PS_STORAGE_PG_URI: ${PS_STORAGE_PG_URI}
